//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RReplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaxDeployableAmount
    {
        public int SourceInstanceId { get; set; }
        public Nullable<byte> SourceClassId { get; set; }
        public Nullable<int> DeployableAmount1 { get; set; }
        public Nullable<int> DeployableAmount2 { get; set; }
        public Nullable<int> DeployableAmount3 { get; set; }
        public Nullable<int> DeployableAmount4 { get; set; }
        public Nullable<int> DeployableAmount5 { get; set; }
    }
}
