//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RReplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nations
    {
        public byte Coalition { get; set; }
        public byte NationID { get; set; }
        public string Description { get; set; }
        public byte[] Hash { get; set; }
    }
}
