//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RReplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class PactUnits
    {
        public int DeckId { get; set; }
        public short SourceClassId { get; set; }
        public int SourceInstanceId { get; set; }
        public byte RefClassId { get; set; }
        public int RefInstanceID { get; set; }
    
        public virtual TUniteAuSol TUniteAuSol { get; set; }
    }
}
