//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RReplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionPrice
    {
        public int SourceInstanceId { get; set; }
        public Nullable<byte> SourceClassId { get; set; }
        public Nullable<int> Price1 { get; set; }
        public Nullable<int> Price2 { get; set; }
        public Nullable<int> Price3 { get; set; }
        public Nullable<int> Price4 { get; set; }
        public Nullable<int> Price5 { get; set; }
    
        public virtual TUniteAuSol TUniteAuSol { get; set; }
    }
}
