//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RReplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowInMenu
    {
        public int SourceInstanceId { get; set; }
        public Nullable<byte> SourceClassId { get; set; }
        public Nullable<bool> ShowMenu1 { get; set; }
        public Nullable<bool> ShowMenu2 { get; set; }
        public Nullable<bool> ShowMenu3 { get; set; }
        public Nullable<bool> ShowMenu4 { get; set; }
        public Nullable<bool> ShowMenu5 { get; set; }
    }
}
