//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RReplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimpleUnit
    {
        public int Id { get; set; }
        public string ClassNameForDebug { get; set; }
        public string UnitName { get; set; }
        public string MotherCountry { get; set; }
        public Nullable<int> Category { get; set; }
        public int Factory { get; set; }
        public string UnitTypeName { get; set; }
        public Nullable<int> TypeUnitValue { get; set; }
        public int DeckId { get; set; }
        public byte Coalition { get; set; }
    }
}
