//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RReplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class TModuleSelector
    {
        public int Id { get; set; }
        public byte ClassId { get; set; }
        public string ControllerName { get; set; }
        public Nullable<byte> RefClassId { get; set; }
        public Nullable<int> RefInstanceID { get; set; }
    }
}
