//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RReplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTypeUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TTypeUnit()
        {
            this.TUniteAuSol = new HashSet<TUniteAuSol>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TypeUnitValue { get; set; }
        public byte[] TypeUnitHintToken { get; set; }
        public byte[] NameInMenuToken { get; set; }
        public string MotherCountry { get; set; }
        public Nullable<int> UnitInfoJaugeType { get; set; }
        public byte[] Training { get; set; }
        public byte[] CIWS { get; set; }
        public byte[] Sailing { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TUniteAuSol> TUniteAuSol { get; set; }
        public virtual Units_Translation_US Units_Translation_US { get; set; }
    }
}
