//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RReplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUniteAuSol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUniteAuSol()
        {
            this.OtanUnits = new HashSet<OtanUnits>();
            this.PactUnits = new HashSet<PactUnits>();
        }
    
        public int Id { get; set; }
        public byte ClassId { get; set; }
        public string DescriptorId { get; set; }
        public string C_ShortDatabaseName { get; set; }
        public string ClassNameForDebug { get; set; }
        public Nullable<bool> StickToGround { get; set; }
        public string ManageUnitOrientation { get; set; }
        public Nullable<float> HitRollSizeModifier { get; set; }
        public Nullable<int> IconeType { get; set; }
        public Nullable<int> PositionInMenu { get; set; }
        public byte[] NameInMenuToken { get; set; }
        public string AliasName { get; set; }
        public int Category { get; set; }
        public Nullable<int> AcknowUnitType { get; set; }
        public int TypeForAcknow { get; set; }
        public Nullable<int> Nationalite { get; set; }
        public string MotherCountry { get; set; }
        public Nullable<int> ProductionYear { get; set; }
        public Nullable<int> MaxPacks { get; set; }
        public int Factory { get; set; }
        public Nullable<int> ProductionTime { get; set; }
        public Nullable<int> CoutEtoile { get; set; }
        public string TextureMotherCountryForInterface { get; set; }
        public Nullable<int> UnitMovingType { get; set; }
        public Nullable<float> VitesseCombat { get; set; }
        public Nullable<bool> IsPrototype { get; set; }
        public Nullable<int> TypeUnitId { get; set; }
        public Nullable<int> FlagsId { get; set; }
        public Nullable<int> WeaponManagerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtanUnits> OtanUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PactUnits> PactUnits { get; set; }
        public virtual Units_Translation_US Units_Translation_US { get; set; }
        public virtual MaxDeployableAmount MaxDeployableAmount { get; set; }
        public virtual ShowInMenu ShowInMenu { get; set; }
        public virtual UnitTypeTokens UnitTypeTokens { get; set; }
        public virtual ProductionPrice ProductionPrice { get; set; }
        public virtual TTypeUnit TTypeUnit { get; set; }
    }
}
