//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RReplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeaponManager
    {
        public int SourceInstanceId { get; set; }
        public Nullable<byte> SourceClassId { get; set; }
        public Nullable<byte> DestinationClassId { get; set; }
        public int DestinationInstanceID { get; set; }
    }
}
